### ISSUE TITLE
Duplicate Shoko Groups

### ISSUE THREAD

**Issue by raf802** [ShokoAnime/Shokofin#19]
I am getting a few duplicates for anime groups that have more than one series.
![shoko](https://user-images.githubusercontent.com/8290514/140495294-30edbb99-631f-48e4-bebf-0821a0eec2b6.JPG)

They have the same metadata and their contents are the same with all of the grouped series. 
This is a clean Library with no metadata .nfo and only Shoko is providing metadata.
The anime series are in separate folders. E.g. "Fate/Stay Night" and "Fate/Zero" are in their own folders inside the library folder "anime".

The issue is not to do with actual seasons of an anime, but related series that are part of the same group.

I believe the issue could be jelly/shokofin sees the individual series folders, finds their group and then applies the group information to each series folder. 

Any suggestions?

**Comment by revam** [comment]
@raf802 First off, sorry for not responding earlier (I'm not so active on GitHub these days).

Now I'm guessing but it seems to me like you've enabled the option to group series into seasons in the plugin settings but haven't enabled the option to merge the series in the library settings.

If you could provide the version of Jellyfin, Shokofin and Shoko Server you're using along with the library settings **for the plugin** (in the plugin settings) that you're using that may help narrow down the problem.

(Also, for faster replies I would recommend heading over to our discord server, as I'm more active there then on GitHub.)

**Comment by revam** [comment]
Closing due to lack of response. Feel free to reopen it if you're still stuck.
