### ISSUE TITLE
Currently shows as unsupported in 10.8.0 Beta 1 and 2

### ISSUE THREAD

**Issue by wreid23** [ShokoAnime/Shokofin#21]
Plugin currently shows as unsupported in 10.8.0 Beta 1 and 2. Running in Docker on Synology NAS

![image](https://user-images.githubusercontent.com/24215762/163741945-7fef5728-66e6-4eb7-b743-3ee95cca9510.png)

Log:
[ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/Shoko_1.7.2.0/Shokofin.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

Method 'ExecuteAsync' in type 'Shokofin.Tasks.ExportUserDataTask' from assembly 'Shokofin, Version=1.7.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Method 'ExecuteAsync' in type 'Shokofin.Tasks.ImportUserDataTask' from assembly 'Shokofin, Version=1.7.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Method 'ExecuteAsync' in type 'Shokofin.Tasks.SyncUserDataTask' from assembly 'Shokofin, Version=1.7.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)

   at System.Reflection.Assembly.GetTypes()
[_AJJELLAY15_logs.txt](https://github.com/ShokoAnime/Shokofin/files/8502927/_AJJELLAY15_logs.txt)

   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()

System.TypeLoadException: Method 'ExecuteAsync' in type 'Shokofin.Tasks.ExportUserDataTask' from assembly 'Shokofin, Version=1.7.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

System.TypeLoadException: Method 'ExecuteAsync' in type 'Shokofin.Tasks.ImportUserDataTask' from assembly 'Shokofin, Version=1.7.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by revam** [comment]
See #20
