### ISSUE TITLE
Automated releases not updating tag

### ISSUE THREAD

**Issue by fearnlj01** [ShokoAnime/Shokofin#40]
Looking at [the list of tags for Shokofin](https://github.com/ShokoAnime/Shokofin/tags), commit [`bef066d`](https://github.com/ShokoAnime/Shokofin/commit/bef066d7fb33426229c7bf8f81a52fcb1d38e951) has ended up being tagged twice with both `2.0.1.40` & `2.0.1.41`.

Running `git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/"` (as per the [`WyriHaximus/github-action-get-previous-tag@v1`](https://github.com/WyriHaximus/github-action-get-previous-tag/blob/master/main.js) action) currently outputs `2.0.1.40` however, which leads to the next attempt at setting a tag to be the already existing `2.0.1.41`...

I'd imagine the easiest resolution would be to manually create tags for `2.0.1.42` & `2.0.1.43` (or just delete the tag for `2.0.1.40`) Don't think I can PR anything like this sadly! 

I can however, as below, include the git commands to create the tags we'd expect if everything played nice at the expected commits however!
```
git tag 2.0.1.42 77980cd50fa6ef3d0094886fe0fc00f2acf21e5c
git tag 2.0.1.43 cc7df47d57226d6be6a49fdab5bf7395f8002c34
```

**Comment by revam** [comment]
Since it's just dailies (no stable release) then I just deleted the existing `2.0.1.40` and `2.0.1.41` and made it recreate `2.0.1.40`.

(I also accidentally closed the wrong issue with my commit, but we don't talk about that.)
