### ISSUE TITLE
Plugin has no settings page

### ISSUE THREAD

**Issue by t3hk0d3** [ShokoAnime/Shokofin#43]
Somehow after installing plugin there is a no way to configure it.

Restarting Jellyfin doesn't fix it.

Jellyfin version: 10.8.11

![Screenshot_20240101_091116](https://github.com/ShokoAnime/Shokofin/assets/86416/decb0bbf-5feb-4f73-86eb-15338b982925)

**Comment by revam** [comment]
did you check the jellyfin log for errors?

**Comment by t3hk0d3** [comment]
@revam Problem has been solved somehow after few restarts/reinstalls.
