### ISSUE TITLE
Shows as unsupported in Jellyfin 10.9.z

### ISSUE THREAD

**Issue by Reinachan** [ShokoAnime/Shokofin#44]
I was testing out the beta to see if it resolved some playback issues and found that this plugin was showing as unsupported. If there's any data you want to help figure out why, just let me know.

Error message from logs

```
Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/Shoko_3.0.1.34/Shokofin.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
```

**Comment by revam** [comment]
It will be supported once 10.9 is officially out (and not just the RCs!), which is not yet.

**Comment by revam** [comment]
Also before anyone even thinks about asking. **It _most likely_ won't be compatible on day 1 of the official 10.9 release**. Just wait for it to be released, or fork it yourself and fix any incompatibilities until it is released. There are stuff to fix internally in the plugin before I even think about updating Jellyfin to introduce new variables that can break things. This isn't directly aimed at Rainachan, but at anyone reading about this about to comment "wen 10.9?" or similar.

**Comment by SteveMavic** [comment]
@revam hi, 10.9.0 and 10.9.1 is finally out there https://github.com/jellyfin/jellyfin/releases
Any news when Shokofin will be supported in Jellyfin 10.9+?

**Comment by revam** [comment]
I know 10.9 is out, but tge plugin will still be released when it's ready, like I said above. 🙂

**Comment by GlassedSilver** [comment]
> I know 10.9 is out, but the plugin will still be released when it's ready, like I said above. 🙂

and when is it ready?




kekekeke just kidding. I want to take this opportunity for doing all this work. You're making the lives of many otaku so much simpler and more convenient. It's invaluable to have your own media collection anywhere you go and Jellyfin is amazing for this for western media, but it'd be sorrowly lacking without your unfettered work and effort to make it a great home for anime alike! So from the bottom of my heart and many others as well I'm sure: thank you so much!

**Comment by revam** [comment]
Forgot to close this.
