### ISSUE TITLE
Proposal: Add a new Series/Sesson/Episode indexer.

### ISSUE THREAD

**Issue by revam** [ShokoAnime/Shokofin#5]
## Proposal

I want Jellyfin's "series" to be used to group together Shoko's series (_all kinds_, e.g. series, web _and_ movies) in something along the lines of Shoko's "groups", where Jellyfin's "sessions" are used to order the items in the group. The "session"'s details will be filled from the series in Shoko,  and the "series"'s details will be filled from the the staring point (not necessary the first "session") of the "group". The starting point will be considered the first release in the group (e.g Fate/Stay Night for the fate series)

All misc. (other and parody), trailers and credits will be grouped at "session" index 97, 98 and 99 respectively, specials will be grouped after the episodes from the series they are in, but in a separate "session" ending with " Specials" (or localized equivalent), and the rest of the episodes will be ordered in one of the following ways:

- **By chronological order** - meaning the first "session" may have been released later then the second "session", and so on. The story is followed from the first prequel to the last sequel.

- **By release date** - meaning the order of which they were released. Some series expand the backstory of the original by releasing a prequel at a later time. The story may jump a bit, if you watch in this order, but sometimes that may be preferred.

### Conflicts

- All Shoko series will be stored under the same "group", so finding a series will be more difficult if you don't know the "group" it belongs to, and individual series will not be searchable.

- Currently undefined behavior when a group of series contain alternate versions with the same prequel/sequel or both. **Help needed!**

### Goal

So if this proposal goes though, we will have three ways to index our library:

- A one-to-one relation between Jellyfin Series and Movies and Shoko Series.

- A one-to-many relation between Jellyfin Series and Shoko Series.

- Whatever TvDB decides. (Because I don't know).

### Implementation To-Do

- [ ] Add a new API call to get all related sequels and prequels for a series. Either prepossessed, or we can to process it client-side.
  - This will be used to set the session order.

- [ ] Modify `Shokofin.Providers.SeriesProvider` to calculate and generate the structure beforehand (including the session and episode tree) if the "add missing" option is enabled on a library.

- [ ] Expand `Shokofin.Providers.SessionProvider` to create better sessions.

- [ ]  We need to somehow add an episode, preferably with both relative and absolute numbering according to our order type.
  - Maybe use `Shokofin.Providers.EpisodeProvider` to optionally recalculate positions on _every_ import if on.

  - Other solutions? **Do tell!**

- [ ] ~~Implement a new `SeriesMetadataService` and `MissingEpisodeProvider`, since the default relays heavily on TvDB ids being present, and creates sessions in a TvDB fasion, and there are no way to only implement the later (since it is a one-off class and not an interface), but for Shoko.~~
    https://github.com/jellyfin/jellyfin/blob/f50348ca0b03a7928e58eb3b188532b98d6f46fa/MediaBrowser.Providers/TV/SeriesMetadataService.cs#L19
    https://github.com/jellyfin/jellyfin/blob/384ab39f5b3dfb940cb9f612f5b64541c9ec935b/MediaBrowser.Providers/TV/MissingEpisodeProvider.cs#L22

**Comment by EraYaN** [comment]
When you mention session do you mean season?

**Comment by revam** [comment]
> When you mention session do you mean season? I think we can have arbitrary season names in Jellyfin, so no need for numbers 97, 98, 99 or something like that.

@EraYaN Yes, I meant season. And no I did not mean the name, but the season index number.

**Comment by EraYaN** [comment]
I suppose in that case the numbers are purely used for ordering and can be arbitrary (I would use some spacing between all of them for future use).

**Comment by revam** [comment]
I think the season numbers should not matter here, and be recalculated if the users changes the ordering method or if a new entry appears (i.e. in-between existing entries, or at the beginning).

**Comment by EraYaN** [comment]
One should definitely use season numbers that plugins like the Trakt one and so on will ignore (so either very high or something like 0 for specials)

**Comment by revam** [comment]
Well, most of the features i wanted here is implemented in #14, so I'm closing this for now.

**Comment by revam** [comment]
The chronological ordering will be added at a later date.

**Comment by GlassedSilver** [comment]
Regarding season naming...

https://github.com/jellyfin/jellyfin/issues/2187

Jellyfin supports custom paths now that go beyond Show / Season 1, 2, .... & Specials.

One could use the following logic:

`Anime / Franchise name (as in the Shoko Group) / Season's show name (either romaji-JP or En or whatever we prefer) <instead of Season 1, 2 , ...>`

Also refer to: https://github.com/jellyfin/jellyfin/issues/2446

You can even put specials within the season now. So no more specials per show (JF), but per season! (if I understood everything correctly!)

Thoughts?
