### ISSUE TITLE
Shokofin not fetching trailers/credits

### ISSUE THREAD

**Issue by sannidhyaroy** [ShokoAnime/Shokofin#65]
### Jellyfin version.

10.9.8

### Shokofin version.

4.1.1.0

### Shoko Server version, release channel, and commit hash.

4.2.2 Stable

### File structure of your _Media Library Folder in Jellyfin_/_Import Folder in Shoko Server_.

../Anime Title/Season X/S0XE0Y: Episode Title

### Screenshot of the "library settings" section of the plugin settings.

<img width="824" alt="Screenshot 2024-07-30 at 7 40 19 PM" src="https://github.com/user-attachments/assets/4e7eaad4-f65b-4308-86f2-c0ffacb6175a">
<img width="826" alt="Screenshot 2024-07-30 at 7 40 32 PM" src="https://github.com/user-attachments/assets/c66ffd8f-9e4b-4c95-9288-e893cfca15f1">

### Library Type(s).

Shows

### Do the issue persists after creating a library with Shoko set as the only metadata provider? (Now is your time to check if you haven't already.)

- [X] Yes, I hereby confirm that the issue persists after creating a library with Shoko set as the only metadata provider.

### Issue

Shokofin doesn’t add trailers for a series (not yet tested for movies, so unsure about that) into a `trailers` folder that Jellyfin supports. I have VFS turned on, so I can’t manually add a trailer either. The same goes for credits as well, but I can live without it, although support for that would be great as well.

**Comment by revam** [comment]
is this a shows type library, or a mixed type library?

**Comment by revam** [comment]
are the trailers recognised in shoko?

**Comment by revam** [comment]
Also, just to be sure, but you don't see this icon in the UI?
![Screenshot_20240730_164503_Jellyfin](https://github.com/user-attachments/assets/4b987004-aa8a-470f-894f-cbf0d0faf4c8)

**Comment by sannidhyaroy** [comment]
> are the trailers recognised in shoko?

I'm new to Shoko, so I'll ask this, just to be sure:
Will Shoko fetch trailers from some online source or do I have to place a trailer into my import folders, and Shoko can check the hash to detect it as a trailer?

If the answer is that Shoko automatically fetches trailers from an online source, is there any way to check that Shoko has indeed fetched a trailer and the issue is specific to Shokofin?

**Comment by revam** [comment]
shoko onpy provide local tdaileds (for mow at least) that are recognised by shoko itself.

**Comment by sannidhyaroy** [comment]
> Also, just to be sure, but you don't see this icon in the UI?

That icon shows up as YouTube Trailers Plugin was enabled for me. If Jellyfin has fetched a YouTube Trailer and there exists a `trailers` folder, Jellyfin will prioritize the media inside the `trailers` and ignore the YouTube Trailers completely.

Since, clicking on that icon loads up a YouTube Trailer, I suspected Shokofin didn't create a `trailers` folder. I confirmed the lack of such folder, when I looked inside the VFS folder to see there were Season `X` folders will symlinks to my episodes, but no `trailers` folder.

I have disabled YouTube Trailers as 90% of the trailers that Jellyfin fetches are region-restricted, so it doesn't load up.

**Comment by sannidhyaroy** [comment]
> shoko onpy provide local tdaileds (for mow at least) that are recognised by shoko itself.

So, I have to manually place a trailer content in my import folders and Shoko should recognize it as a trailer. Is that correct?

**Comment by revam** [comment]
You can either

- create a trailer folder in the VFS entry for the show/season and place the youtube video you downloaded in there, followed by a refresh of the show/season in Jellyfin afterwards, _or_

- you can add a trailer to shoko (either automagically through hash recognition or manually by linking using Shoko Desktop), and it will automagically be linked to the trailer folder for the show and season in Jellyfin.

**Comment by revam** [comment]
> EDIT: I downloaded a trailer from YouTube and threw it in Shoko's import folder. It categorized it as "Unrecognized".

That is intended behaviour if hash recognition doesn't work btw. You need to manually link anything that is not indexed on AniDB (or add it if it's a public release, which the downloaded youtube video is not).

**Comment by revam** [comment]
If there is a plugin that places files in a `trailer` sub-directory for the show/season then it should in theory work fine even with the VFS (provided they've written it to work with relative paths the same way Jellyfin would resolve the trailers). Not that I've done any research to check if there are any.
