### ISSUE TITLE
Specials Position not handled properly

### ISSUE THREAD

**Issue by sannidhyaroy** [ShokoAnime/Shokofin#66]
<img width="875" alt="Screenshot 2024-07-30 at 7 51 14 PM" src="https://github.com/user-attachments/assets/e8054a8a-8057-4864-af4e-74fb6da61e12">

Specials Placement works perfectly when the default option (placed after normal episodes) is selected. #37 resolved the last option as well (to exclude specials within seasons). The remaining options still don’t work for me (yes, I have deleted and recreated the library), and selecting any of those will just work as the default option (place specials after seasons).

**Comment by revam** [comment]
Last time I checked, then the release date option works fine (using it for my library). But  I can try to investigate if that still is the case in 10.9.

**Comment by sannidhyaroy** [comment]
> Last time I checked, then the release date option works fine (using it for my library). But  I can try to investigate if that still is the case in 10.9.

For more context, I noticed it in the anime called "The Dangers in my Heart" or "BokuYaba". I have Season 1 and Season 2 and 1 OVA (inside Specials). The OVA is released after Season 1 and before Season 2, but Shoko places it at the end of Season 2, no matter what.

I can see that Shokofin has set the release date of the OVA correctly, but using the `Release Date` option in Shoko still places it after Season 2.


### Expected Result:
The OVA should be placed either after the episodes of Season 1 or before the episodes of Season 2. When Shoko is disabled and TVDB is used on a library, this expected result is achieved.

**Comment by revam** [comment]
Looking at the AniAD entries then the expected result wod be to place it in season 2, _before_ all normal episodes.

My brain is twlling me that there might be a flaw in the placement logic for such episodes that would be placed before all episodes in the season because we determing the placement based _the previous_ normal episode, which there is none off. I'll look at it after work to see if it can be improved upon.

**Comment by revam** [comment]
I'll get to this next time I have time to sit down and fix the _minor inconveniences_ that have cropped up so far.

**Comment by sannidhyaroy** [comment]
> I'll get to this next time I have time to sit down and fix the _minor inconveniences_ that have cropped up so far.

No problem, please take your time. Thanks for this amazing plugin.

**Comment by revam** [comment]
Do re-open the issue if this didn't fix it. @sannidhyaroy 

Also, you may need to manually clear the specials placement data if it's incorrect… on every affected episode you want to fix it, or just recreate the whole library from a clean slate. I don't know if they've made it so the specials placement is cleared when you do a full rescan of the metadata in 10.9, but it certainly wasn't so in 10.8.
