### ISSUE TITLE
Wrong "Mapped Import Folder" in SignalR Settings

### ISSUE THREAD

**Issue by TheBlueKingLP** [ShokoAnime/Shokofin#68]
### Jellyfin version.

10.9.7

### Shokofin version.

4.0.0.20

### Shoko Server version, release channel, and commit hash.

4.2.2.0 (59f051c) Dev

### File structure of your _Media Library Folder in Jellyfin_/_Import Folder in Shoko Server_.

Jellyfin: /media/TVアニメ/Series/Episode.mkv
Shoko: /mnt/anime/TVアニメ/Series/Episode.mkv

### Screenshot of the "library settings" section of the plugin settings.

![image](https://github.com/user-attachments/assets/1dbc5077-2532-4b84-824c-42f0bd350de1)

### Library Type(s).

Shows

### Do the issue persists after creating a library with Shoko set as the only metadata provider? (Now is your time to check if you haven't already.)

- [X] Yes, I hereby confirm that the issue persists after creating a library with Shoko set as the only metadata provider.

### Issue

The path in the "Mapped Import Folder" in Shokofin settings is incorrect
![image](https://github.com/user-attachments/assets/9c722e84-07e9-4efc-addb-6985efdefe0e)

**Comment by revam** [comment]
first things first, update your shokofin version @TheBlueKingLP

**Comment by revam** [comment]
and as i said on discord, I'll look at it later (when i have time)

**Comment by revam** [comment]
Until I get to root cause during testing, then you can try to manually reset or fix the mapping.

If you want to attempt that, then you can start by opening the `Shokofin.xml` inside the `configurations` directory in the Jellyfin plugins directory, then either a) editing the path to be correct (look at your movie library to see how it should be when the root of the media folder is mapped to the root of the import folder), or b) by removing the media folder node entirely and refreshing the TV media library.

**Comment by revam** [comment]
@TheBlueKingLP did this fix itself at some point or is it still wrong?

**Comment by TheBlueKingLP** [comment]
> @TheBlueKingLP did this fix itself at some point or is it still wrong?

Seems to be still wrong as of this moment, on Shoko 5.0.0.0 and Shokofin 4.0.0.20

**Comment by revam** [comment]
Shokofin 4.0.0.20 is not compatible with Shoko Server 5.0.0.0. Update to at least Jellyfin 10.9.7 or newer and Shokofin 4.2.0.0 or newer to have compatible versions for all three components (Jellyfin, Shokofin & Shoko Server).

**Comment by revam** [comment]
For context; we debugged the issue over discord and found the root cause of the issue, and it has now been fixed as a result.
