### ISSUE TITLE
Collection Overview has incorrect format for links

### ISSUE THREAD

**Issue by sannidhyaroy** [ShokoAnime/Shokofin#71]
<img src="https://github.com/user-attachments/assets/4a65a07b-52b9-49c2-914a-13b59ed10887" alt="Jellyfin Collections Page">

### Issue:
Shokofin sets incorrect format for links in the overview section for collections. There are no such issues for shows and movies.

### Explanation:
Jellyfin supports embedding links in the overview section, in a similar way we write in markdown like `[link text](link address)` and Shokofin takes advantage of it, but for collections, it uses a format like `link address [link text]`, which is an invalid format.

DETAILS:
Shoko Server: v4.2.2.0 Stable
Shokofin: v4.1.1.0 Stable

**Comment by revam** [comment]
It's because we didn't sanitize the group description. Thanks for the report.

**Comment by revam** [comment]
Though next time, please use the issue template. 😔
